version: '3'
services:
  studio:
    build:
      context: ./
      dockerfile: Dockerfile-jamdisplay 
    volumes:
      - type: volume
       source: ./read
        target: /jam/volumes/data
        read-only: true
      - type: volume
        source: ./write
        target: /jam/volumes/outputs
        read-only: false
    ports:
      - "8080:80"
    restart: always

  db:
    image: mysql:5.7
    volumes:
        # Pass volume named mysql-data to mysql container
      - "mysql-data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jam
      MYSQL_DATABASE: jam
      MYSQL_USER: jam
      MYSQL_PASSWORD: jam
    ports:
      - "8080:80"

volumes:
  mysql-data:
    driver: cio
    driver_opts:
      profile: "MYSQL"
